import 'bootstrap/dist/css/bootstrap.css'
import Head from 'next/head'
import { createGlobalStyle } from "styled-components";
const GloabalStyle = createGlobalStyle`
  a,a:hover{
    text-decoration:none;
    /* color: white; */
  }
  .row{
    margin:80px 0 !important;
  }
`
function MyApp({ Component, pageProps }) {
  return (<div>
    <Head>
      <title>Viessmann</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="https://www.designfreelogoonline.com/wp-content/uploads/2018/06/01001-modern-V-Logo-02.png" />
    </Head>
    <GloabalStyle />
    <Component {...pageProps} />
  </div>)
}

export default MyApp
